#!/bin/bash

### BEGIN INIT INFO
# Provides:   craftbukkit
# Required-Start: $local_fs $remote_fs
# Required-Stop:  $local_fs $remote_fs
# Should-Start:   $network
# Should-Stop:    $network
# Default-Start:  2 3 4 5
# Default-Stop:   0 1 6
# Short-Description:    Craftbukkit server
# Description:    Init script for craftbukkit server
### END INIT INFO

if test -f /etc/default/craftbukkit; then
    . /etc/default/craftbukkit
fi

is_running(){
    if ps aux | grep "java.*${CRAFTBUKKIT_JAR}" | grep -v "su\|grep"  > /dev/null
    then
        return 0
    fi
    return 1
}

cb_server_cmd() {
    if is_running
    then
        screen -p 0 -S $SCREEN -X eval "stuff \"$1\"\015"
    else
        echo "Craftbukkit was not running. Not able to execute command."
    fi
}
cb_say() {
    cb_server_cmd "say $1"
}
cb_save() {
    cb_server_cmd "save-all"
}
cb_save_off() {
    cb_server_cmd "save-off"
    sync
    sleep 10
}
cb_save_on() {
    cb_server_cmd "save-on"
}


cb_start() {
    # cd $CRAFTBUKKIT_PATH
    cd $CRAFTBUKKIT_PATH
    screen -dmS $SCREEN
    screen -p 0 -S $SCREEN -X exec su $USERNAME -s /bin/bash -c "$INVOCATION"

    seconds=0
    until is_running 
    do
        sleep 1
        seconds=$seconds+1
        if [[ $seconds -eq 5 ]]
        then
            echo "Still not running, waiting a while longer..."
        fi
        if [[ $seconds -ge 120 ]]
        then
            echo "Failed to start, aborting."
            exit 1
        fi
    done    
    echo "Craftbukkit is running."
}

cb_stop() {
    echo "Sending message to all users to indicate the server is shutting down. Wait for 10 seconds."
    cb_say "SERVER SHUTTING DOWN IN 10 SECONDS"
    cb_save
    sleep 10
    cb_server_cmd "stop"
    sleep 1

    seconds=0
    while is_running 
    do
        sleep 1
        seconds=$seconds+1
        if [[ $seconds -eq 5 ]]
        then
            echo "Still running, waiting a while longer..."
        fi
        if [[ $seconds -ge 120 ]]
        then
            echo "Failed to stop, aborting."
            exit 1
        fi
    done

    screen -p 0 -S $SCREEN -X quit

    echo "Craftbukkit is stopped."
}

cb_overviewer() {
    if is_running
    then
        cb_say "Starting overviewer. Might cause a little lag."
        cb_save
        cb_save_off
    fi

    overviewer.py -p 1 --config=/etc/overviewer/config.py --simple-output > /dev/null

    if is_running
    then
        cb_save_on
        cb_say "Map regenerated"
    fi
}

case "$1" in
    start)
        if is_running
        then
            echo "Craftbukkit already running. No starting."
            exit 1
        else
            cb_start
        fi
        ;;
    stop)
        if is_running
        then
            cb_stop
        else
            echo "Craftbukkit not running. No starting."
            exit 1
        fi
        ;;
    status)
        # Shows server status
        if is_running
        then
            echo "running."
        else
            echo "not running."
        fi
        ;;
    say)
        cb_say "$2"
        ;;
    overviewer)
        cb_overviewer
        ;;
    *)
        echo "No such command, see $0 help"
        exit 1
        ;;
esac